### ISSUE TITLE
base64 library conflict

### ISSUE THREAD

**Issue by ffppmm** [magicshifter/MS3000#4]
Hi,

working with the MK3 Firmware I noticed that sometimes, newer platformio version, the wrong header file base64.h gets included. Maybe you should rename base64.h and base64.cpp from the lib directory to something like Base64_adamvr.

Platformio version 2.8.5 brings their own base64 implemetation! Maybe there is a flag in platformio.ini that gives the lib directory higher priority.

thx

**Comment by seclorum** [comment]
Hi @ffppmm .. thanks for reporting this.  I've checked with the latest PlatformIO version (2.8.5) and did not see how I could force pio to include the platformio-included base64.h header before our own lib/Base64/Base64.h version .. it would be very beneficial to understand how it is "sometimes, the wrong header gets included".  Are you compiling things with our Makefile, or some other method?

Could you send me a copy of the build-log for a case when this occurs?

(Also, are you using a case-sensitive filesystem?  base64.h != Base64.h - perhaps this is why "sometimes" the build pulls in the wrong file - but I'd like to be as deterministic as possible in addressing this ..)

**Comment by ffppmm** [comment]
Hi,

yes you are right, I run platformio in the Atom IDE/Editor on Windows. I got it compiled with little efford after renaming the file (maybe refactoring the class to reflect the filename change whould be good). Crossplatform should include Windows systems :)

**Comment by seclorum** [comment]
Looking further into this, I discovered that this issue is triggered if you do not delete the .pioenvs build product directory before attempting to build the main MS3KOS bin.  PlatformIO makes .pioenvs (*) when we 'make', but 'make test' may get confused about the 'freshness' of .pioenvs, which leads to the paths being inverted.

Thinking about this, the larger issue for me is that _build-products-dependencies-rules_ are being forced on us by PlatformIO.  I'd rather just build everything from scratch - libs first, then the ESP objects, then our main objects linked to our known-libs, and thus produce the firmware - every time you type 'make'.  PlatformIO does this, but alas, .pioenvs gets stale.

So I have a personal preference to not be too dependent on PlatformIO - we can easily switch to the esp8266-gcc or other compiler under our own local config if needed, or at least should be able to going forward .. so instead of do this Base64 dance, I've just added a 'make clean' target to our Makefile, which resolves this issue administratively and also dis-imposes the PlatformIO constraints upon our environment (of which this issue is symptomatic).

(*- I despise this, so I'm going to add a BUILD_PRODUCTS_DIR:= override soon, too..)

**Comment by seclorum** [comment]
This is a non-issue - do 'make clean && make test monitor' to build properly.
