### ISSUE TITLE
Latencies when Wifi is on

### ISSUE THREAD

**Issue by ChrisVeigl** [magicshifter/MS3000#6]
just noticed random "blackouts" during image POV when Wifi is turned on (hotspot configuration). These dropouts are quite short and show up as a few missing "columns" in the image display. 
(In my setup there was no active connection to the MS3000 hotspot. The dropouts seemed to disappear when i established connection).

Another issue which might be related: when Wifi is turned on, the "bouncing ball" display slows down considerably.... (thus the MS cannot be used as a tubular level anymore - which is IMO a very neat feature)

**Comment by seclorum** [comment]
Apropros Wifi-impact-on-bouncing-ball - this is a clear bug and we are currently working on this performance issue, since it is significant to the continued high-performance of our environment.

Thanks for reporting this - should have something to report soon and we will definitely address this for the next firmware release.

**Comment by ChrisVeigl** [comment]
Thanks ! 
maybe also worth noting: when wifi is turned off in the "values" mode, it is re-enabled after the MS3000 was put to sleep and is then switched on again... (is this on purpose ?)

**Comment by seclorum** [comment]
This issue has been fixed - we addressed the performance issues with WiFi in the latest firmware release.  Please update and verify if you get the chance:

http://github.com/magicshifter/MS3000/releases/latest/
